
all: AI_Unius_Mentis.png Alien_Wing.png Interocitor_Flux_Capacitor.png Mars_Spider.png Quad_Flux_Capacitor_Caged.png Transparent_Blue_Harpoon-Grapler.png Transparent_Yellow_Harpoon-Grapler.png

%.png: %.psd
	convert $< -resize 250x250 $@

